# Generated by Django 2.2 on 2021-05-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('fav_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='of_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authenticate.User'),
            preserve_default=False,
        ),
    ]
