# Generated by Django 2.2 on 2021-06-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books', '0002_book_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='of_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_books', to='authenticate.User'),
        ),
    ]
